### ISSUE TITLE
Add option to open without splitting window

### ISSUE THREAD

**Issue by jemminger** [harada4atsushi/rails-open-rspec#12]
I'd like my specs to open just in a new tab, not by splitting the window

**Comment by harada4atsushi** [comment]
How is [rails-rspec](https://atom.io/packages/rails-rspec)?
It can toggle file in the same tab.

**Comment by harada4atsushi** [comment]
> [rails-rspec](https://atom.io/packages/rails-rspec)というパッケージはどうでしょうか？
> これは同じtabでファイルをトグルできます

**Comment by jemminger** [comment]
Perfect, thanks
