### ISSUE TITLE
Question: Support for minitest or any known alternative?

### ISSUE THREAD

**Issue by mariozaizar** [harada4atsushi/rails-open-rspec#13]
Hello, I'm looking for minitest support, or looking for any alternative that works as well as yours.

Thanks in advance!

Mario

**Comment by dcarral** [comment]
Hi Mario, 

Taking into account that your message is from November 2015, you've probably already found [ruby-test-switcher](https://github.com/dcarral/atom-ruby-test-switcher)... just in case ;)

**Comment by harada4atsushi** [comment]
@dcarral Thank you for answer, I was helped.
