### ISSUE TITLE
new tests for files under /lib folder

### ISSUE THREAD

**Issue by sunkibaek** [harada4atsushi/rails-open-rspec#14]
Hi,

Thanks for the great package. It's really handy -- I don't have to type in the filenames in fuzzy finder.

But one issue I have found while using it is when I try to make a new test file under `lib/` folder it seems to make a new file under the same folder as the original file instead of `spec/lib/` folder.

Hope this can be fixed. I'll try to implement it myself, too, if you don't mind :-)
Thanks!

**Comment by harada4atsushi** [comment]
@sunkibaek 
Thanks!
Just a moment please. I am translating.

**Comment by harada4atsushi** [comment]
> いけてるパッケージをありがとう。これは本当に便利です。おかげでファイルネームでfuzzy finderで検索する必要がなくなった。
> 
> でもひとつ課題があって、libの下にあるファイルのテストを作成するときに、spec/libの代わりにオリジナルと同じフォルダーに作成されてしまうことを発見した。
> 
> これが修正すでに修正されている可能性を希望する。もしよろしければ、自分自身で実装して直してみます。
> ありがとう！

**Comment by harada4atsushi** [comment]
@sunkibaek 
Hi,

Thank you for using this package. I'm glad to get impressions. 

Do I hear that you correct this issue? I would like to need your help very much.

Thanks. 
- I am poor at English. I am sorry if I cannot understand.

**Comment by harada4atsushi** [comment]
> このパッケージを使ってくれてありがとうございます。
> 感想もらえて嬉しいです。
> 
> あなたが修正してくれるということですか？
> ぜひpull requestいただけると嬉しいです。
> よろしくお願いします。
> 
> ※ 英語が不得意でうまく理解出来ていなかったらすみません。

**Comment by harada4atsushi** [comment]
fixed #18

**Comment by sunkibaek** [comment]
:+1:
