### ISSUE TITLE
テストファイルが存在していない場合に、ファイルが新規作成されない挙動に変更するオプションが欲しい

### ISSUE THREAD

**Issue by ghost** [harada4atsushi/rails-open-rspec#16]
こんにちは。毎日、便利に使わせて頂いています。
テストファイルが存在しないファイル上で`option-cmd-o`を実行すると、新規にテストファイルが作成される挙動だと思っています。
新規にテストファイルが作成されず、`テストファイルが存在しません`等の文言が表示される挙動があると便利かなぁーと考えています。

**Comment by harada4atsushi** [comment]
@takiy33 要望ありがとうございます。設定でそういうオプションを追加しても良いかもですね。

デフォルトの挙動をどちらにすべきか検討したいのですが、specが新規作成されてしまうと、どういうときに不便ですか？

**Comment by ghost** [comment]
> デフォルトの挙動をどちらにすべきか検討したいのですが、specが新規作成されてしまうと、どういうときに不便ですか？

個人の感覚的なものになって申し訳ないのですが、僕は手癖でCtrl + s(保存)を良く実行してしまいます。
なので、以下の手順の時、少し不便かなぁーと感じました。
1. ファイル上で、option-cmd-o(テストファイルを開く)を実行する。
2. テストファイルが新規に作成される。
3. ctrl-s(ファイルを保存)を実行する。

この時、コントローラーに対するテストなど、あえてテストを書いていなかった場合に不要なファイルが保存されてしまいます。

**Comment by harada4atsushi** [comment]
@takiy33 なるほどなるほど。ありがとうございます。参考にさせていただきます。
